In [4]:
import numpy as np


In [8]:
a1 = np.arange(10)


In [9]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(a1.shape)

(10,)


In [11]:
a2 = np.arange(0,10,2)
print(a2)

[0 2 4 6 8]


In [12]:
a3 = np.zeros(4)
a3

array([0., 0., 0., 0.])

In [13]:
a4 = np.zeros((2,3))
a4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a4.shape

(2, 3)

In [15]:
a5 = np.full((2,4),8)

In [16]:
a5

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [17]:
a6 = np.eye(4)

In [19]:
a6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
a7 = np.random.random((2,4))
a7

array([[0.51293148, 0.04187619, 0.18515119, 0.18771972],
       [0.42974333, 0.52537652, 0.59154254, 0.62084146]])

In [23]:
list1 = [1,2,3,4,5]
r1 = np.array(list1)
r1

array([1, 2, 3, 4, 5])

In [25]:
list2 = [6,7,8,9,10]
r2 = np.array([list1, list2])

In [26]:
r2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
r2.shape

(2, 5)

In [28]:
r1 > 2

array([False, False,  True,  True,  True])

In [29]:
r1[r1>2]

array([3, 4, 5])

In [30]:
nums = np.arange(20)

In [31]:
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
odds_nums = nums[nums %2 ==1 ]

In [33]:
odds_nums

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [38]:
b1 = a[1:3, :3]

In [39]:
b1

array([[4, 5, 6],
       [6, 7, 8]])

In [41]:
b4 = np.array([1,2,3,4,5,6])
b4.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print("hello")

: 